# Generated by Django 4.0.3 on 2022-03-29 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(choices=[('2', '2'), ('1', '1')], default='1', max_length=1)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prof_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating2', models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('3', '3'), ('1', '1')], default='1', max_length=1)),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.module')),
                ('professor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
                ('rating', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Prof_Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.module')),
                ('professor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Dep_Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Dep_Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.module')),
            ],
        ),
    ]
