# Generated by Django 4.0.3 on 2022-03-29 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_mod',
            name='rating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.rating'),
        ),
        migrations.AlterField(
            model_name='prof_rating',
            name='rating2',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('2', '2'), ('5', '5')], default='1', max_length=1),
        ),
    ]
