# Generated by Django 4.0.3 on 2022-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_prof_mod_rating_alter_prof_rating_rating2'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(default='CF', max_length=10),
        ),
        migrations.AlterField(
            model_name='prof_rating',
            name='rating2',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('5', '5'), ('4', '4'), ('1', '1')], default='1', max_length=1),
        ),
    ]
