# Generated by Django 4.0.3 on 2022-03-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_module_module_code_alter_prof_rating_rating2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='prof_rating',
            name='rating2',
            field=models.CharField(choices=[('5', '5'), ('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], default='1', max_length=1),
        ),
    ]
